# Generated by Django 5.1.3 on 2024-12-08 16:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Models',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=75, verbose_name='modelning oti')),
                ('model_bio', models.TextField(blank=True, null=True, verbose_name='model xaqida malumot')),
                ('model_logo', models.ImageField(blank=True, null=True, upload_to='photos/', verbose_name='model rasmi')),
            ],
        ),
        migrations.CreateModel(
            name='Cars',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('car_name', models.CharField(max_length=100, unique=True, verbose_name='moshina oti')),
                ('car_bio', models.TextField(blank=True, null=True, verbose_name='Moshina haqida malaumot')),
                ('car_color', models.CharField(max_length=50, verbose_name='moshina rangi')),
                ('photo', models.ImageField(upload_to='photos/', verbose_name='moshina rasmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.TimeField(auto_now=True, null=True)),
                ('model', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='new.models', verbose_name='modelni kiriting')),
            ],
        ),
    ]
